project_root: "."
experiment_id: "synth_pop" 
#One of ["synth_pop", "vanilla"]
# data_version: "v1.2"
# parameters:
#   rush_hour_start: 07:00
#   rush_hour_end: 09:00

modules:
  shapefiles: "0-shapefiles"
  synthetic_population: "0-synthetic-population"
  trips: "1-trips"
  assign_activities: "2-assign_activities"
  locations: "3-locations"
  assign_locations: "4-assign_locations"
  synthetic_population_to_sim: "5-synthetic_population_to_Sim2APL"
  routing : "6-routing"


#For each experiment_id, you need to define which synthetic population is used,
#and which households etc. 
configuration:
  vanilla: 
    module_dir: "0-synthetic-population/output/synthetic-population-households"
    population: "synthetic_population_DHZW_2019.csv"
    households: "df_households_DHZW_2019.csv"
  synth_pop:
    module_dir: "0-synthetic-population/output/gen-synth-pop"
    population:  "synthetic_population_the_hague_south_west.csv"
    households: "synthetic_households_the_hague_south_west.csv"
    