project_root: "."
experiment_id: "synth_pop"
data_version: "v1.2"
parameters:
  rush_hour_start: 07:00
  rush_hour_end: 09:00

modules:
  shapefiles: "0-shapefiles"
  synthetic_population: "0-synthetic-population"
  trips: "1-trips"
  assign_activities: "2-assign_activities"
  locations: "3-locations"
  assign_locations: "4-assign_locations"
  synthetic_population_to_sim: "5-synthetic_population_to_Sim2APL"
  routing : "6-routing"
