[simulation]
startdate = 2026-03-30
iterations = 7 # Number of days, or end date


[config]
base_dir = "src/main/resources/"
population_source_folder = "gen-synth-pop"
experiment_id = "gen-synth-pop"
distribution_output_base_folder = "src/main/resources/distance_analysis/"
activities = ["DHZW_full/DHZW_activities_locations.csv"]
households = ["DHZW_full/DHZW_households.csv"]
persons = ["DHZW_full/DHZW_synthetic_population.csv"]
routing_walk = ["routing/walk_time_distance.csv"]
routing_bike = ["routing/bike_time_distance.csv"]
routing_car = ["routing/car_time_distance.csv"]
routing_bus_tram = ["routing/routing_bus.csv"]
routing_train = ["routing/routing_train.csv"]
beeline_distance = ["routing/beeline_distance.csv"]
seed=2929243944